Lots of changes

diff --git a/bcpe b/bcpe
--- a/bcpe
+++ b/bcpe
@@ -1,7 +1,14 @@
 #!/bin/bash
 
 # An editor to design custom command prompts.
-# Quick overview of the code: Since there are certain ASCII codes that only work in the command prompt, and since some 'items' have different lengths of characters, three main string variables exist. One is used to store the design while in the editor (easy_edit_form), another one to display your design in the editor (display_form), and finally the actual string that is saved (full_form). A design is saved by adding a few lines to the end of your .bashrc file. Since a .bashrc file is rather useful, it is backed up prior to saving in case something goes wrong, and is saved as '.bashrc_backup_made_by_bcpe'.
+# Quick overview of the code: Since there are certain ASCII codes that only work 
+# in the command prompt, and since some 'items' have different lengths of characters, 
+# three main string variables exist. One is used to store the design while in the 
+# editor (easy_edit_form), another one to display your design in the editor 
+# (display_form), and finally the actual string that is saved (full_form).
+# A design is saved by adding a few lines to the end of your .bashrc file.
+# Since a .bashrc file is rather useful, it is backed up prior to saving in case 
+# something goes wrong, and is saved as '.bashrc_backup_made_by_bcpe'.
 
 # Some variables
 easy_edit_form=""
@@ -13,28 +20,43 @@ extra_message=""
 main_seg_active=1
 var_for_cutting=1
 check_this_out="blank"
-error_reason="Reason unknown."
 
 # Functions
-terminate_due_to_error () {
-  echo "The program has been terminated due to error:"
-  echo "$error_reason"
-  echo "Please report this issue."
+
+# A function to prompt/read an interactive y/n response
+# Stops reading after one character, meaning only 'y' or 'Y' will return 0
+# _anything_ else will return 1
+confirm() {
+  read -rn 1 -p "${*:-Continue} [Y/N]? "
+  printf -- '%s\n' ""
+  case "${REPLY}" in
+    ([yY]) return 0 ;;
+    (*)    return 1 ;;
+  esac
+}
+
+die() {
+  printf -- '%s\n' \
+    "The program has been terminated due to error:"
+    "${*:Reason unknown}" \
+    "Please report this issue." >&2
   exit 1
 }
 
 # Displayed several times at the top of the screen
 header () {
   clear
-  echo "
-  --- Command Prompt Editor ---
-  "
-  echo ""
-  echo "---"
-  echo -e $display_form
-  echo "---"
-  echo $extra_message
-  echo ""
+  cat << EOF
+
+--- Command Prompt Editor ---
+
+
+---
+${display_form}
+---
+${extra_message}
+
+EOF
 }
 
 # Its a very basic loading animation.
@@ -47,13 +69,42 @@ sleep_dot () {
   done
 }
 
+usage() {
+  cat << EOF
+'q!' to force quit. 'wr' to write/enable custom prompt.
+'rm' to remove last char/item. 'ex' to export as .txt to share your design.
+Item codes:
+sp - Insert a 'space'.
+1a - Makes computer beep when printed. May not work on all systems.
+1b - Current date. Format: Weekday Month Date (ex: Mon January 3)
+1c - Hostname of the machine, with the trailing domain name removed.
+1d - Full hostname.
+1e - Number of jobs being run by the shell.
+1f - Name of the terminal device.
+1g - Name of the shell program.
+1h - Time in 24 hour format, HH:MM:SS.
+1i - Time in 12 hour format, HH:MM:SS.
+1j - Time in 12 hour AM/PM format.
+1k - Time in 24 hour format, HH:MM.
+1l - Username of the current user.
+1m - The version of bash in use (x.xx).
+1n - The release of bash in use (x.xx.x).
+1o - The full name of the current directory (ex: ~/Documents/School/Project).
+1p - The last part of the name of the current directory (ex: /Project).
+1q - The history number of this command.
+1r - The number of commands run in this shell session.
+1s - Displays a $ if logged in as user, instead displays a # if logged in as root.
+
+EOF
+}
+
 # Updates the variable 'full_form' drawing info from the variable 'easy_edit_form'
 update_full_form () {
-  echo "Updating full form."
+  printf -- '%s\n' "Updating full form."
   var_for_cutting=1
-  while [[ "$var_for_cutting" -le "$size_of_easy_edit_form" ]]; do
-    check_this_out=$(echo $easy_edit_form | cut -d '%' -f $var_for_cutting)
-    case "$check_this_out" in
+  while (( var_for_cutting <= size_of_easy_edit_form )); do
+    check_this_out=$(printf -- '%s\n' $easy_edit_form | cut -d '%' -f $var_for_cutting)
+    case "${check_this_out}" in
       # Items
       (1a)  full_form+="\[\a\]" ;;
       (1b)  full_form+="\d" ;;
@@ -78,8 +129,7 @@ update_full_form () {
       (?)  full_form+=$check_this_out ;;
       # Something that should not be there
       (*)
-        error_reason="Something was found in the sting used to store your custom command line prior to saving it that definetly should not be there."
-        terminate_due_to_error
+        die "Custom command line string contains something that definitely should not be there."
       ;;
     esac
     var_for_cutting=$((var_for_cutting+1))
@@ -89,13 +139,13 @@ update_full_form () {
 
 # Updates the variable 'display_form' with info from variable 'easy_edit_form'
 update_display_form () {
-  echo "Updating display form."
+  printf -- '%s\n' "Updating display form."
   var_for_cutting=1
   display_form=""
   extra_message=""
-  while [[ "$var_for_cutting" -le "$size_of_easy_edit_form" ]]; do
-    check_this_out=$(echo $easy_edit_form | cut -d '%' -f $var_for_cutting)
-    case "$check_this_out" in
+  while (( var_for_cutting <= size_of_easy_edit_form )); do
+    check_this_out=$(printf -- '%s\n' $easy_edit_form | cut -d '%' -f $var_for_cutting)
+    case "${check_this_out}" in
       # Items
       (1a)     
         display_form+="(Non-visable beep char.)"
@@ -127,67 +177,43 @@ update_display_form () {
   return
 }
 
-# Starts from here
-echo "Running this editor will clear your shell, do you want to continue? (y/n)"
-read -r start_confirm
-if [ "$start_confirm" != "y" ] && [ "$start_confirm" != "Y" ]; then
-  echo "Quiting..."; exit
-else
+# Last chance to escape
+if ! confirm "Running this editor will clear your shell, do you want to continue?"; then
+  die "Quitting..."
+fi
 
-echo "If you have not used this editor before, or if you need a refresher, instructions can be found in the README file."
+# Starts from here
+printf -- '%s\n' "If you have not used this editor before, or if you need a refresher, instructions can be found in the README file."
 sleep_dot 4
 begin_writing="no"
-while [ "$begin_writing" == "no" ]; do # This while loop contains the editor and the color choosing, and exists in order to allow someone to return to the editor prior to saving.
-  while [ "$main_seg_active" == 1 ]; do # This while loop contains the bulk of the editor.
+# This while loop contains the editor and the color choosing, and exists in order 
+# to allow someone to return to the editor prior to saving.
+while [[ "${begin_writing}" = "no" ]]; do
+  # This while loop contains the bulk of the editor.
+  while [[ "${main_seg_active}" = 1 ]]; do
     update_display_form
     add_seperator=true
     header
-    echo "'q!' to force quit. 'wr' to write/enable custom prompt."
-    echo "'rm' to remove last char/item. 'ex' to export as .txt to share your design."
-    echo "Item codes:"
-    echo "sp - Insert a 'space'."
-    echo "1a - Makes computer beep when printed. May not work on all systems."
-    echo "1b - Current date. Format: Weekday Month Date (ex: Mon January 3)"
-    echo "1c - Hostname of the machine, with the trailing domain name removed."
-    echo "1d - Full hostname."
-    echo "1e - Number of jobs being run by the shell."
-    echo "1f - Name of the terminal device."
-    echo "1g - Name of the shell program."
-    echo "1h - Time in 24 hour format, HH:MM:SS."
-    echo "1i - Time in 12 hour format, HH:MM:SS."
-    echo "1j - Time in 12 hour AM/PM format."
-    echo "1k - Time in 24 hour format, HH:MM."
-    echo "1l - Username of the current user."
-    echo "1m - The version of bash in use (x.xx)."
-    echo "1n - The release of bash in use (x.xx.x)."
-    echo "1o - The full name of the current directory (ex: ~/Documents/School/Project)."
-    echo "1p - The last part of the name of the current directory (ex: /Project)."
-    echo "1q - The history number of this command."
-    echo "1r - The number of commands run in this shell session."
-    echo "1s - Displays a $ if logged in as user, instead displays a # if logged in as root."
-    echo ""
-    echo "Enter a single character, or a two character command/item: "
+    usage
+    printf -- '%s\n' "Enter a single character, or a two character command/item: "
     read -r input_selection
-    case "$input_selection" in
+    case "${input_selection}" in
       (%)
-        echo "I'm sorry, you cannot use a '%' sign. Any other character is allowed!"
+        printf -- '%s\n' "I'm sorry, you cannot use a '%' sign. Any other character is allowed!"
         add_seperator=false
         sleep_dot 3
       ;;
       (sp)  easy_edit_form+=" " ;;
       # Commands
-      (q!)
-        echo "Program has been manually terminated."
-        exit
-      ;;
+      (q!) die "Program has been manually terminated." ;;
       (rm) 
         if ((size_of_easy_edit_form>0)); then
           size_of_easy_edit_form=$((size_of_easy_edit_form-1))
-          easy_edit_form=$(echo "$easy_edit_form" | cut -d '%' -f 1-$size_of_easy_edit_form)
+          easy_edit_form=$(printf -- '%s\n' "${easy_edit_form}" | cut -d '%' -f 1-${size_of_easy_edit_form})
           # Here, the size is reduced again, but the loss is made of for in the 'if' right below this 'case'
           size_of_easy_edit_form=$((size_of_easy_edit_form-1)) 
           else
-          echo "There is nothing to delete!"
+          printf -- '%s\n' "There is nothing to delete!"
           add_seperator=false
           sleep_dot 3
         fi
@@ -197,19 +223,19 @@ while [ "$begin_writing" == "no" ]; do # This while loop contains the editor and
         add_seperator=false
       ;;
       (ex)
-        echo "Sorry! Exporting is not yet supported."
+        printf -- '%s\n' "Sorry! Exporting is not yet supported."
         add_seperator=false
         sleep_dot 3
       ;;
       # Items
       (1[a-s])  easy_edit_form+=$input_selection ;;
       (*)
-        echo "Error! Remember, characters must be entered one at a time! / Error! That is not a valid multi-char code!"
+        printf -- '%s\n' "Error! Remember, characters must be entered one at a time! / Error! That is not a valid multi-char code!"
         add_seperator=false
         sleep_dot 4
       ;;
     esac
-    if [ "$add_seperator" == "true" ]; then
+    if [[ "$add_seperator" == "true" ]]; then
       easy_edit_form+="%"
       size_of_easy_edit_form=$((size_of_easy_edit_form+1))
     fi
@@ -218,7 +244,7 @@ while [ "$begin_writing" == "no" ]; do # This while loop contains the editor and
   # Here the color is choosen.
   update_display_form
   second_seg_active=1
-  while [ "$second_seg_active" == 1 ]; do
+  while [[ "$second_seg_active" == 1 ]]; do
     header
     printf -- '%s\n' "Select a color:"
     printf -- '%s\t\033[1;37m%s\t\033[0;30m%s\t\033[0;31m%s\n' \
@@ -230,7 +256,7 @@ while [ "$begin_writing" == "no" ]; do # This while loop contains the editor and
     printf -- '\033[1;32m%s\t\033[1;33m%s\t\033[1;34m%s\t\033[1;35m%s\n' \
       "Light Green - 13" "Yellow - 14" "Light Blue - 15" "Light Purple - 16"
     printf -- '\033[1;372m%s\033[0;37m\n' "Light Cyan - 17"
-    echo "Enter corresponding number:"
+    printf -- '%s\n' "Enter corresponding number:"
     read -r color
     full_form=""
     defaultselected=false
@@ -259,17 +285,17 @@ while [ "$begin_writing" == "no" ]; do # This while loop contains the editor and
     esac
   done # End of color choosing 'while'
   update_full_form
-  if [ "$defaultselected" != "true" ]; then
+  if [[ "$defaultselected" != "true" ]]; then
     full_form+="\[\033[0m\] "
   fi
   confirm_seg_active=1
-  while [ "$confirm_seg_active" == 1 ]; do # This while loop contain the writing confirmation.
+  while [[ "$confirm_seg_active" == 1 ]]; do # This while loop contain the writing confirmation.
     clear
-    echo "
+    printf -- '%s\n' "
     --- Command Prompt Editor ---
     "
-    echo ""
-    echo "Enable command prompt:
+    printf -- '%s\n' ""
+    printf -- '%s\n' "Enable command prompt:
     $display_form
     With color: $colour
     (y/n)"
@@ -282,24 +308,24 @@ while [ "$begin_writing" == "no" ]; do # This while loop contains the editor and
       ([nN]|[nN][oO]) 
         confirm_seg_active=0
         clear
-        echo "What would you like to do?
+        printf -- '%s\n' "What would you like to do?
           - return to the editor (Enter '1'.)
           - quit without saving (Enter anything else.)"
         read -r return_or_quit
-        if [ "$return_or_quit" == 1 ]; then
-          echo "Returning to editor..."
+        if [[ "$return_or_quit" == 1 ]]; then
+          printf -- '%s\n' "Returning to editor..."
         else
-          echo "Program was manually terminated."
+          printf -- '%s\n' "Program was manually terminated."
           exit
         fi
       ;;
-      *) : ;;  
+      (*) : ;;  
     esac
   done
 done
 
 # The actual saving/enabling takes place here:
-echo "Saving..."
+printf -- '%s\n' "Saving..."
 bashrc=$(less ~/.bashrc)
 bashrc+="
 # ---Added by the custom command prompt editor---"
@@ -310,8 +336,7 @@ bashrc+="
 # ---End added by the custom command prompt editor---"
 mv ~/.bashrc ~/.bashrc_backup_made_by_bcpe
 touch ~/.bashrc
-echo "$bashrc" | cat > ~/.bashrc
-echo "To take effect, you need to start a new shell session. (Close and re-open your terminal.)"
-echo "If you wish to undo any changes made, check the README file."
-echo "Program complete."
-fi # end of the start confirmation if
+printf -- '%s\n' "${bashrc}" | cat > ~/.bashrc
+printf -- '%s\n' "To take effect, you need to start a new shell session. (Close and re-open your terminal.)"
+printf -- '%s\n' "If you wish to undo any changes made, check the README file."
+printf -- '%s\n' "Program complete."
